[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[compat]
BenchmarkTools = "1"
SciMLBase = "1.92.0"
Trixi = "0.8.10"
julia = "1.9"
