[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
OrdinaryDiffEqLowStorageRK = "b0944070-b475-4768-8dec-fb6eb410534d"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[compat]
BenchmarkTools = "1"
julia = "1.9"
