[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
ADTypes = "1.18.0"
BenchmarkTools = "1"
Bonito = "3"
JSON = "0.21"
SciMLBase = "1.92.0"
Trixi = "0.8.10"
WGLMakie = "0.9, 0.10"
julia = "1.9"
