name = "BenchmarkExplorerCore"
uuid = "8b8c1e0a-1234-5678-9abc-def012345678"
authors = ["Yaroslav Kachur <yaraslauprogj@example.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "1"
JSON = "0.21"
julia = "1.9"
